### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by Pierdab** [madmappersoftware/Ponk#2]
Hi, I can' figure out how I can make it work. I correctly load the custom OP in touchdesigner and start with the example provided in this repo.
However, I can't find the live inputs in madmapper. Do I need to copy something in madmapper folder, or do I miss something else?

**Comment by mattbeghin** [comment]
Do you have a MadLaser licence ?
macOS or Windows ?
Is MadMapper up to date ?

**Comment by Pierdab** [comment]
Problem solved updateing Madmapper. Thanks 🙏🏻
