### ISSUE TITLE
Madlaser laser Ponk to touchdesigner

### ISSUE THREAD

**Issue by Lightcraftlasers** [madmappersoftware/Ponk#3]
Hi there 

Its unclear how to receive Ponk data into touchdesigner 

I have been able to send data from touchdesigner to madmapper from going off the samples (works great, thank you!!), however I am struggling to make it work in the other direction - I'm not that experienced with UDPs and don't know where to start

Madmapper can publish laser output to Ponk, but its not clear how to set this up as an input into Touchdesigner as a SOP

Any guidance or samples/examples would be greatly appreciated

**Comment by mattbeghin** [comment]
The C++ SDK of Touch Designer doesn't allow creating an input plugin. I can't tell you exactly what's missing but Derivative team asked us (Colas Frizman & me) to pay for the missing SDK feature development. As it's an open source project with no budget and we didn't have the requirement, we just haven't done PONK as input for Touch Designer. But you can contact derivative to request PONK input.

**Comment by colasf** [comment]
Hi,
We didn't implement ponk input in touchdesigner because we where not really seeing an intereset for it at the time.
Could you tell us what is your use case ?
Cheers,
Colas

**Comment by Lightcraftlasers** [comment]
Thanks for the response - I was aiming to create line materials in madmapper to then edit the colour textures in TD to send back to madmapper. So essentialy laser lines that match the colours of video content on the same projection surface, as if the lines were LED strips. 

I found a workaround in madmapper to layer the desired colour layer on top of a video output of the laser lines, using the multiply function. Then loop this again as video throughput to laser material using paths and colour. 

For reference the reply that closed this thread: 
_The C++ SDK of Touch Designer doesn't allow creating an input plugin. I can't tell you exactly what's missing but Derivative team asked us (Colas Frizman & me) to pay for the missing SDK feature development. As it's an open source project with no budget and we didn't have the requirement, we just haven't done PONK as input for Touch Designer. But you can contact derivative to request PONK input._

**Comment by mattbeghin** [comment]
```
or reference the reply that closed this thread:
The C++ SDK of Touch Designer doesn't allow creating an input plugin. I can't tell you exactly what's missing but Derivative team asked us (Colas Frizman & me) to pay for the missing SDK feature development. As it's an open source project with no budget and we didn't have the requirement, we just haven't done PONK as input for Touch Designer. But you can contact derivative to request PONK input.
```

I closed it because I think that was a mistake. The missing feature in the C++ API was the possibility to read some data (is a shape closed or not). Colas knows Touch Designer API, I don't, so I just removed my answer
