### ISSUE TITLE
Unable to detect PONK in Madmapper

### ISSUE THREAD

**Issue by cosmic1** [madmappersoftware/Ponk#4]
I downloaded an opened the TouchDesigner PONK samples but I am unable to receive the PONK data in Mad Mapper. I'm using a Windows 10 PC with MadMapper 5.6.1 (also tested with 5.5.6). To be safe I also tried compiling the plugin myself but nothing seems to be showing up and there is no documentation on how to setup the MadMapper end (I assume this is all automatic but I seem to be missing something).

To be clear I did not modify the example project when testing other than trying a CPlusPlus SOP directed at the PONK dll when the demo failed to work.

**Comment by mattbeghin** [comment]
In MadMapper, the Ponk stream appears in Medias list / Live Inputs as soon as MadMapper receives the first packet. In Touch designer, is the Ponk node Destination IP set to 127.0.0.1 ? Can you try setting your local IP (lan or wifi) ?
Also be sure you authorized both Touch Designer and MadMapper to access network (you can try to disable firewall to be sure the packets are going through). There's no known issue. Let me know the results of those tests.

**Comment by cosmic1** [comment]
@mattbeghin That was it. I had tried all 3 different IPs for my local PC but it looks like I was being blocked by Windows Firewall. I'm not entirely sure why since NDI and OSC were both making it through without any issues but after disabling it entirely the PONK signal came through.
